keymap:
- name: xremap-python
  remap:
    A: A
    Alt-A: Alt-A
    Alt-B: KPSlash
    Alt-C: Alt-C
    Alt-Comma: Down
    Alt-D: Alt-E
    Alt-Dot: Right
    Alt-E: Alt-Comma
    Alt-F: Alt-I
    Alt-G: KPAsterisk
    Alt-H: KPPlus
    Alt-I: Alt-D
    Alt-J: BackSpace
    Alt-K: Up
    Alt-L: Delete
    Alt-M: Left
    Alt-N: KPMinus
    Alt-O: Alt-Y
    Alt-P: Alt-P
    Alt-Q: Alt-Q
    Alt-R: Alt-Dot
    Alt-S: Alt-O
    Alt-Semicolon: Alt-N
    Alt-Shift-A: Alt-Shift-A
    Alt-Shift-B: Alt-Shift-F
    Alt-Shift-C: Alt-Shift-C
    Alt-Shift-Comma: Alt-Shift-J
    Alt-Shift-D: Alt-Shift-E
    Alt-Shift-Dot: Alt-Shift-L
    Alt-Shift-E: Alt-Shift-Comma
    Alt-Shift-F: Alt-Shift-I
    Alt-Shift-G: Alt-Shift-U
    Alt-Shift-H: Alt-Shift-G
    Alt-Shift-I: Alt-Shift-D
    Alt-Shift-J: Alt-Shift-T
    Alt-Shift-K: Alt-Shift-K
    Alt-Shift-L: Alt-Shift-S
    Alt-Shift-M: Alt-Shift-H
    Alt-Shift-N: Alt-Shift-B
    Alt-Shift-O: Alt-Shift-Y
    Alt-Shift-P: Alt-Shift-P
    Alt-Shift-Q: Alt-Shift-Q
    Alt-Shift-R: Alt-Shift-Dot
    Alt-Shift-S: Alt-Shift-O
    Alt-Shift-Semicolon: Alt-Shift-N
    Alt-Shift-Super-A: Alt-Shift-Super-A
    Alt-Shift-Super-B: Alt-Shift-Super-F
    Alt-Shift-Super-C: Alt-Shift-Super-C
    Alt-Shift-Super-Comma: Alt-Shift-Super-J
    Alt-Shift-Super-D: Alt-Shift-Super-E
    Alt-Shift-Super-Dot: Alt-Shift-Super-L
    Alt-Shift-Super-E: Alt-Shift-Super-Comma
    Alt-Shift-Super-F: Alt-Shift-Super-I
    Alt-Shift-Super-G: Alt-Shift-Super-U
    Alt-Shift-Super-H: Alt-Shift-Super-G
    Alt-Shift-Super-I: Alt-Shift-Super-D
    Alt-Shift-Super-J: Alt-Shift-Super-T
    Alt-Shift-Super-K: Alt-Shift-Super-K
    Alt-Shift-Super-L: Alt-Shift-Super-S
    Alt-Shift-Super-M: Alt-Shift-Super-H
    Alt-Shift-Super-N: Alt-Shift-Super-B
    Alt-Shift-Super-O: Alt-Shift-Super-Y
    Alt-Shift-Super-P: Alt-Shift-Super-P
    Alt-Shift-Super-Q: Alt-Shift-Super-Q
    Alt-Shift-Super-R: Alt-Shift-Super-Dot
    Alt-Shift-Super-S: Alt-Shift-Super-O
    Alt-Shift-Super-Semicolon: Alt-Shift-Super-N
    Alt-Shift-Super-T: Alt-Shift-Super-Semicolon
    Alt-Shift-Super-U: Alt-Shift-Super-R
    Alt-Shift-Super-V: Alt-Shift-Super-V
    Alt-Shift-Super-X: Alt-Shift-Super-X
    Alt-Shift-Super-Y: Alt-Shift-Super-M
    Alt-Shift-Super-Z: Alt-Shift-Super-Z
    Alt-Shift-T: Alt-Shift-Semicolon
    Alt-Shift-U: Alt-Shift-R
    Alt-Shift-V: Alt-Shift-V
    Alt-Shift-X: Alt-Shift-X
    Alt-Shift-Y: Alt-Shift-M
    Alt-Shift-Z: Alt-Shift-Z
    Alt-Super-A: Alt-Super-A
    Alt-Super-B: Alt-Super-F
    Alt-Super-C: Alt-Super-C
    Alt-Super-Comma: Alt-Super-J
    Alt-Super-D: Alt-Super-E
    Alt-Super-Dot: Alt-Super-L
    Alt-Super-E: Alt-Super-Comma
    Alt-Super-F: Alt-Super-I
    Alt-Super-G: Alt-Super-U
    Alt-Super-H: Alt-Super-G
    Alt-Super-I: Alt-Super-D
    Alt-Super-J: Alt-Super-T
    Alt-Super-K: Alt-Super-K
    Alt-Super-L: Alt-Super-S
    Alt-Super-M: Alt-Super-H
    Alt-Super-N: Alt-Super-B
    Alt-Super-O: Alt-Super-Y
    Alt-Super-P: Alt-Super-P
    Alt-Super-Q: Alt-Super-Q
    Alt-Super-R: Alt-Super-Dot
    Alt-Super-S: Alt-Super-O
    Alt-Super-Semicolon: Alt-Super-N
    Alt-Super-T: Alt-Super-Semicolon
    Alt-Super-U: Alt-Super-R
    Alt-Super-V: Alt-Super-V
    Alt-Super-X: Alt-Super-X
    Alt-Super-Y: Alt-Super-M
    Alt-Super-Z: Alt-Super-Z
    Alt-T: Alt-Semicolon
    Alt-U: Alt-R
    Alt-V: Alt-V
    Alt-X: Alt-X
    Alt-Y: Alt-M
    Alt-Z: Alt-Z
    B: F
    C: C
    Comma: J
    Ctrl-A: Ctrl-A
    Ctrl-Alt-A: Ctrl-Alt-A
    Ctrl-Alt-B: Ctrl-Alt-F
    Ctrl-Alt-C: Ctrl-Alt-C
    Ctrl-Alt-Comma: Ctrl-Alt-J
    Ctrl-Alt-D: Ctrl-Alt-E
    Ctrl-Alt-Dot: Ctrl-Alt-L
    Ctrl-Alt-E: Ctrl-Alt-Comma
    Ctrl-Alt-F: Ctrl-Alt-I
    Ctrl-Alt-G: Ctrl-Alt-U
    Ctrl-Alt-H: Ctrl-Alt-G
    Ctrl-Alt-I: Ctrl-Alt-D
    Ctrl-Alt-J: Ctrl-Alt-T
    Ctrl-Alt-K: Ctrl-Alt-K
    Ctrl-Alt-L: Ctrl-Alt-S
    Ctrl-Alt-M: Ctrl-Alt-H
    Ctrl-Alt-N: Ctrl-Alt-B
    Ctrl-Alt-O: Ctrl-Alt-Y
    Ctrl-Alt-P: Ctrl-Alt-P
    Ctrl-Alt-Q: Ctrl-Alt-Q
    Ctrl-Alt-R: Ctrl-Alt-Dot
    Ctrl-Alt-S: Ctrl-Alt-O
    Ctrl-Alt-Semicolon: Ctrl-Alt-N
    Ctrl-Alt-Shift-A: Ctrl-Alt-Shift-A
    Ctrl-Alt-Shift-B: Ctrl-Alt-Shift-F
    Ctrl-Alt-Shift-C: Ctrl-Alt-Shift-C
    Ctrl-Alt-Shift-Comma: Ctrl-Alt-Shift-J
    Ctrl-Alt-Shift-D: Ctrl-Alt-Shift-E
    Ctrl-Alt-Shift-Dot: Ctrl-Alt-Shift-L
    Ctrl-Alt-Shift-E: Ctrl-Alt-Shift-Comma
    Ctrl-Alt-Shift-F: Ctrl-Alt-Shift-I
    Ctrl-Alt-Shift-G: Ctrl-Alt-Shift-U
    Ctrl-Alt-Shift-H: Ctrl-Alt-Shift-G
    Ctrl-Alt-Shift-I: Ctrl-Alt-Shift-D
    Ctrl-Alt-Shift-J: Ctrl-Alt-Shift-T
    Ctrl-Alt-Shift-K: Ctrl-Alt-Shift-K
    Ctrl-Alt-Shift-L: Ctrl-Alt-Shift-S
    Ctrl-Alt-Shift-M: Ctrl-Alt-Shift-H
    Ctrl-Alt-Shift-N: Ctrl-Alt-Shift-B
    Ctrl-Alt-Shift-O: Ctrl-Alt-Shift-Y
    Ctrl-Alt-Shift-P: Ctrl-Alt-Shift-P
    Ctrl-Alt-Shift-Q: Ctrl-Alt-Shift-Q
    Ctrl-Alt-Shift-R: Ctrl-Alt-Shift-Dot
    Ctrl-Alt-Shift-S: Ctrl-Alt-Shift-O
    Ctrl-Alt-Shift-Semicolon: Ctrl-Alt-Shift-N
    Ctrl-Alt-Shift-Super-A: Ctrl-Alt-Shift-Super-A
    Ctrl-Alt-Shift-Super-B: Ctrl-Alt-Shift-Super-F
    Ctrl-Alt-Shift-Super-C: Ctrl-Alt-Shift-Super-C
    Ctrl-Alt-Shift-Super-Comma: Ctrl-Alt-Shift-Super-J
    Ctrl-Alt-Shift-Super-D: Ctrl-Alt-Shift-Super-E
    Ctrl-Alt-Shift-Super-Dot: Ctrl-Alt-Shift-Super-L
    Ctrl-Alt-Shift-Super-E: Ctrl-Alt-Shift-Super-Comma
    Ctrl-Alt-Shift-Super-F: Ctrl-Alt-Shift-Super-I
    Ctrl-Alt-Shift-Super-G: Ctrl-Alt-Shift-Super-U
    Ctrl-Alt-Shift-Super-H: Ctrl-Alt-Shift-Super-G
    Ctrl-Alt-Shift-Super-I: Ctrl-Alt-Shift-Super-D
    Ctrl-Alt-Shift-Super-J: Ctrl-Alt-Shift-Super-T
    Ctrl-Alt-Shift-Super-K: Ctrl-Alt-Shift-Super-K
    Ctrl-Alt-Shift-Super-L: Ctrl-Alt-Shift-Super-S
    Ctrl-Alt-Shift-Super-M: Ctrl-Alt-Shift-Super-H
    Ctrl-Alt-Shift-Super-N: Ctrl-Alt-Shift-Super-B
    Ctrl-Alt-Shift-Super-O: Ctrl-Alt-Shift-Super-Y
    Ctrl-Alt-Shift-Super-P: Ctrl-Alt-Shift-Super-P
    Ctrl-Alt-Shift-Super-Q: Ctrl-Alt-Shift-Super-Q
    Ctrl-Alt-Shift-Super-R: Ctrl-Alt-Shift-Super-Dot
    Ctrl-Alt-Shift-Super-S: Ctrl-Alt-Shift-Super-O
    Ctrl-Alt-Shift-Super-Semicolon: Ctrl-Alt-Shift-Super-N
    Ctrl-Alt-Shift-Super-T: Ctrl-Alt-Shift-Super-Semicolon
    Ctrl-Alt-Shift-Super-U: Ctrl-Alt-Shift-Super-R
    Ctrl-Alt-Shift-Super-V: Ctrl-Alt-Shift-Super-V
    Ctrl-Alt-Shift-Super-X: Ctrl-Alt-Shift-Super-X
    Ctrl-Alt-Shift-Super-Y: Ctrl-Alt-Shift-Super-M
    Ctrl-Alt-Shift-Super-Z: Ctrl-Alt-Shift-Super-Z
    Ctrl-Alt-Shift-T: Ctrl-Alt-Shift-Semicolon
    Ctrl-Alt-Shift-U: Ctrl-Alt-Shift-R
    Ctrl-Alt-Shift-V: Ctrl-Alt-Shift-V
    Ctrl-Alt-Shift-X: Ctrl-Alt-Shift-X
    Ctrl-Alt-Shift-Y: Ctrl-Alt-Shift-M
    Ctrl-Alt-Shift-Z: Ctrl-Alt-Shift-Z
    Ctrl-Alt-Super-A: Ctrl-Alt-Super-A
    Ctrl-Alt-Super-B: Ctrl-Alt-Super-F
    Ctrl-Alt-Super-C: Ctrl-Alt-Super-C
    Ctrl-Alt-Super-Comma: Ctrl-Alt-Super-J
    Ctrl-Alt-Super-D: Ctrl-Alt-Super-E
    Ctrl-Alt-Super-Dot: Ctrl-Alt-Super-L
    Ctrl-Alt-Super-E: Ctrl-Alt-Super-Comma
    Ctrl-Alt-Super-F: Ctrl-Alt-Super-I
    Ctrl-Alt-Super-G: Ctrl-Alt-Super-U
    Ctrl-Alt-Super-H: Ctrl-Alt-Super-G
    Ctrl-Alt-Super-I: Ctrl-Alt-Super-D
    Ctrl-Alt-Super-J: Ctrl-Alt-Super-T
    Ctrl-Alt-Super-K: Ctrl-Alt-Super-K
    Ctrl-Alt-Super-L: Ctrl-Alt-Super-S
    Ctrl-Alt-Super-M: Ctrl-Alt-Super-H
    Ctrl-Alt-Super-N: Ctrl-Alt-Super-B
    Ctrl-Alt-Super-O: Ctrl-Alt-Super-Y
    Ctrl-Alt-Super-P: Ctrl-Alt-Super-P
    Ctrl-Alt-Super-Q: Ctrl-Alt-Super-Q
    Ctrl-Alt-Super-R: Ctrl-Alt-Super-Dot
    Ctrl-Alt-Super-S: Ctrl-Alt-Super-O
    Ctrl-Alt-Super-Semicolon: Ctrl-Alt-Super-N
    Ctrl-Alt-Super-T: Ctrl-Alt-Super-Semicolon
    Ctrl-Alt-Super-U: Ctrl-Alt-Super-R
    Ctrl-Alt-Super-V: Ctrl-Alt-Super-V
    Ctrl-Alt-Super-X: Ctrl-Alt-Super-X
    Ctrl-Alt-Super-Y: Ctrl-Alt-Super-M
    Ctrl-Alt-Super-Z: Ctrl-Alt-Super-Z
    Ctrl-Alt-T: Ctrl-Alt-Semicolon
    Ctrl-Alt-U: Ctrl-Alt-R
    Ctrl-Alt-V: Ctrl-Alt-V
    Ctrl-Alt-X: Ctrl-Alt-X
    Ctrl-Alt-Y: Ctrl-Alt-M
    Ctrl-Alt-Z: Ctrl-Alt-Z
    Ctrl-B: Ctrl-F
    Ctrl-C: Ctrl-C
    Ctrl-Comma: Ctrl-J
    Ctrl-D: Ctrl-E
    Ctrl-Dot: Ctrl-L
    Ctrl-E: Ctrl-Comma
    Ctrl-F: Ctrl-I
    Ctrl-G: Ctrl-U
    Ctrl-H: Ctrl-G
    Ctrl-I: Ctrl-D
    Ctrl-J: Ctrl-T
    Ctrl-K: Ctrl-K
    Ctrl-L: Ctrl-S
    Ctrl-M: Ctrl-H
    Ctrl-N: Ctrl-B
    Ctrl-O: Ctrl-Y
    Ctrl-P: Ctrl-P
    Ctrl-Q: Ctrl-Q
    Ctrl-R: Ctrl-Dot
    Ctrl-S: Ctrl-O
    Ctrl-Semicolon: Ctrl-N
    Ctrl-Shift-A: Ctrl-Shift-A
    Ctrl-Shift-B: Ctrl-Shift-F
    Ctrl-Shift-C: Ctrl-Shift-C
    Ctrl-Shift-Comma: Ctrl-Shift-J
    Ctrl-Shift-D: Ctrl-Shift-E
    Ctrl-Shift-Dot: Ctrl-Shift-L
    Ctrl-Shift-E: Ctrl-Shift-Comma
    Ctrl-Shift-F: Ctrl-Shift-I
    Ctrl-Shift-G: Ctrl-Shift-U
    Ctrl-Shift-H: Ctrl-Shift-G
    Ctrl-Shift-I: Ctrl-Shift-D
    Ctrl-Shift-J: Ctrl-Shift-T
    Ctrl-Shift-K: Ctrl-Shift-K
    Ctrl-Shift-L: Ctrl-Shift-S
    Ctrl-Shift-M: Ctrl-Shift-H
    Ctrl-Shift-N: Ctrl-Shift-B
    Ctrl-Shift-O: Ctrl-Shift-Y
    Ctrl-Shift-P: Ctrl-Shift-P
    Ctrl-Shift-Q: Ctrl-Shift-Q
    Ctrl-Shift-R: Ctrl-Shift-Dot
    Ctrl-Shift-S: Ctrl-Shift-O
    Ctrl-Shift-Semicolon: Ctrl-Shift-N
    Ctrl-Shift-Super-A: Ctrl-Shift-Super-A
    Ctrl-Shift-Super-B: Ctrl-Shift-Super-F
    Ctrl-Shift-Super-C: Ctrl-Shift-Super-C
    Ctrl-Shift-Super-Comma: Ctrl-Shift-Super-J
    Ctrl-Shift-Super-D: Ctrl-Shift-Super-E
    Ctrl-Shift-Super-Dot: Ctrl-Shift-Super-L
    Ctrl-Shift-Super-E: Ctrl-Shift-Super-Comma
    Ctrl-Shift-Super-F: Ctrl-Shift-Super-I
    Ctrl-Shift-Super-G: Ctrl-Shift-Super-U
    Ctrl-Shift-Super-H: Ctrl-Shift-Super-G
    Ctrl-Shift-Super-I: Ctrl-Shift-Super-D
    Ctrl-Shift-Super-J: Ctrl-Shift-Super-T
    Ctrl-Shift-Super-K: Ctrl-Shift-Super-K
    Ctrl-Shift-Super-L: Ctrl-Shift-Super-S
    Ctrl-Shift-Super-M: Ctrl-Shift-Super-H
    Ctrl-Shift-Super-N: Ctrl-Shift-Super-B
    Ctrl-Shift-Super-O: Ctrl-Shift-Super-Y
    Ctrl-Shift-Super-P: Ctrl-Shift-Super-P
    Ctrl-Shift-Super-Q: Ctrl-Shift-Super-Q
    Ctrl-Shift-Super-R: Ctrl-Shift-Super-Dot
    Ctrl-Shift-Super-S: Ctrl-Shift-Super-O
    Ctrl-Shift-Super-Semicolon: Ctrl-Shift-Super-N
    Ctrl-Shift-Super-T: Ctrl-Shift-Super-Semicolon
    Ctrl-Shift-Super-U: Ctrl-Shift-Super-R
    Ctrl-Shift-Super-V: Ctrl-Shift-Super-V
    Ctrl-Shift-Super-X: Ctrl-Shift-Super-X
    Ctrl-Shift-Super-Y: Ctrl-Shift-Super-M
    Ctrl-Shift-Super-Z: Ctrl-Shift-Super-Z
    Ctrl-Shift-T: Ctrl-Shift-Semicolon
    Ctrl-Shift-U: Ctrl-Shift-R
    Ctrl-Shift-V: Ctrl-Shift-V
    Ctrl-Shift-X: Ctrl-Shift-X
    Ctrl-Shift-Y: Ctrl-Shift-M
    Ctrl-Shift-Z: Ctrl-Shift-Z
    Ctrl-Super-A: Ctrl-Super-A
    Ctrl-Super-B: Ctrl-Super-F
    Ctrl-Super-C: Ctrl-Super-C
    Ctrl-Super-Comma: Ctrl-Super-J
    Ctrl-Super-D: Ctrl-Super-E
    Ctrl-Super-Dot: Ctrl-Super-L
    Ctrl-Super-E: Ctrl-Super-Comma
    Ctrl-Super-F: Ctrl-Super-I
    Ctrl-Super-G: Ctrl-Super-U
    Ctrl-Super-H: Ctrl-Super-G
    Ctrl-Super-I: Ctrl-Super-D
    Ctrl-Super-J: Ctrl-Super-T
    Ctrl-Super-K: Ctrl-Super-K
    Ctrl-Super-L: Ctrl-Super-S
    Ctrl-Super-M: Ctrl-Super-H
    Ctrl-Super-N: Ctrl-Super-B
    Ctrl-Super-O: Ctrl-Super-Y
    Ctrl-Super-P: Ctrl-Super-P
    Ctrl-Super-Q: Ctrl-Super-Q
    Ctrl-Super-R: Ctrl-Super-Dot
    Ctrl-Super-S: Ctrl-Super-O
    Ctrl-Super-Semicolon: Ctrl-Super-N
    Ctrl-Super-T: Ctrl-Super-Semicolon
    Ctrl-Super-U: Ctrl-Super-R
    Ctrl-Super-V: Ctrl-Super-V
    Ctrl-Super-X: Ctrl-Super-X
    Ctrl-Super-Y: Ctrl-Super-M
    Ctrl-Super-Z: Ctrl-Super-Z
    Ctrl-T: Ctrl-Semicolon
    Ctrl-U: Ctrl-R
    Ctrl-V: Ctrl-V
    Ctrl-X: Ctrl-X
    Ctrl-Y: Ctrl-M
    Ctrl-Z: Ctrl-Z
    D: E
    Dot: L
    E: Comma
    F: I
    G: U
    H: G
    I: D
    J: T
    K: K
    L: S
    M: H
    N: B
    O: Y
    P: P
    Q: Q
    R: Dot
    S: O
    Semicolon: N
    Shift-A: Shift-A
    Shift-B: Shift-F
    Shift-C: Shift-C
    Shift-Comma: Shift-J
    Shift-D: Shift-E
    Shift-Dot: Shift-L
    Shift-E: Shift-Comma
    Shift-F: Shift-I
    Shift-G: Shift-U
    Shift-Grave: KatakanaHiragana
    Shift-H: Shift-G
    Shift-I: Shift-D
    Shift-J: Shift-T
    Shift-K: Shift-K
    Shift-L: Shift-S
    Shift-M: Shift-H
    Shift-N: Shift-B
    Shift-O: Shift-Y
    Shift-P: Shift-P
    Shift-Q: Shift-Q
    Shift-R: Shift-Dot
    Shift-S: Shift-O
    Shift-Semicolon: Shift-N
    Shift-Super-A: Shift-Super-A
    Shift-Super-B: Shift-Super-F
    Shift-Super-C: Shift-Super-C
    Shift-Super-Comma: Shift-Super-J
    Shift-Super-D: Shift-Super-E
    Shift-Super-Dot: Shift-Super-L
    Shift-Super-E: Shift-Super-Comma
    Shift-Super-F: Shift-Super-I
    Shift-Super-G: Shift-Super-U
    Shift-Super-H: Shift-Super-G
    Shift-Super-I: Shift-Super-D
    Shift-Super-J: Shift-Super-T
    Shift-Super-K: Shift-Super-K
    Shift-Super-L: Shift-Super-S
    Shift-Super-M: Shift-Super-H
    Shift-Super-N: Shift-Super-B
    Shift-Super-O: Shift-Super-Y
    Shift-Super-P: Shift-Super-P
    Shift-Super-Q: Shift-Super-Q
    Shift-Super-R: Shift-Super-Dot
    Shift-Super-S: Shift-Super-O
    Shift-Super-Semicolon: Shift-Super-N
    Shift-Super-T: Shift-Super-Semicolon
    Shift-Super-U: Shift-Super-R
    Shift-Super-V: Shift-Super-V
    Shift-Super-X: Shift-Super-X
    Shift-Super-Y: Shift-Super-M
    Shift-Super-Z: Shift-Super-Z
    Shift-T: Shift-Semicolon
    Shift-U: Shift-R
    Shift-V: Shift-V
    Shift-X: Shift-X
    Shift-Y: Shift-M
    Shift-Z: Shift-Z
    Super-A: Super-A
    Super-B: Super-F
    Super-C: Super-C
    Super-Comma: Super-J
    Super-D: Super-E
    Super-Dot: Super-L
    Super-E: Super-Comma
    Super-F: Super-I
    Super-G: Super-U
    Super-H: Super-G
    Super-I: Super-D
    Super-J: Super-T
    Super-K: Super-K
    Super-L: Super-S
    Super-M: Super-H
    Super-N: Super-B
    Super-O: Super-Y
    Super-P: Super-P
    Super-Q: Super-Q
    Super-R: Super-Dot
    Super-S: Super-O
    Super-Semicolon: Super-N
    Super-T: Super-Semicolon
    Super-U: Super-R
    Super-V: Super-V
    Super-X: Super-X
    Super-Y: Super-M
    Super-Z: Super-Z
    T: Semicolon
    U: R
    V: V
    X: X
    Y: M
    Z: Z
modmap:
- name: xremap-python
  remap:
    Alt_R: Super_L
    CapsLock: Control_L

