keymap:
- name: xremap-python
  remap:
    A: A
    Alt-A: Alt-A
    Alt-B: Alt-F
    Alt-C: Alt-C
    Alt-Comma: Alt-J
    Alt-Ctrl-A: Alt-Ctrl-A
    Alt-Ctrl-B: Alt-Ctrl-F
    Alt-Ctrl-C: Alt-Ctrl-C
    Alt-Ctrl-Comma: Alt-Ctrl-J
    Alt-Ctrl-D: Alt-Ctrl-E
    Alt-Ctrl-Dot: Alt-Ctrl-L
    Alt-Ctrl-E: Alt-Ctrl-Comma
    Alt-Ctrl-F: Alt-Ctrl-I
    Alt-Ctrl-G: Alt-Ctrl-U
    Alt-Ctrl-H: Alt-Ctrl-G
    Alt-Ctrl-I: Alt-Ctrl-D
    Alt-Ctrl-J: Alt-Ctrl-T
    Alt-Ctrl-K: Alt-Ctrl-K
    Alt-Ctrl-L: Alt-Ctrl-S
    Alt-Ctrl-M: Alt-Ctrl-H
    Alt-Ctrl-N: Alt-Ctrl-B
    Alt-Ctrl-O: Alt-Ctrl-Y
    Alt-Ctrl-P: Alt-Ctrl-P
    Alt-Ctrl-Q: Alt-Ctrl-Q
    Alt-Ctrl-R: Alt-Ctrl-Dot
    Alt-Ctrl-S: Alt-Ctrl-O
    Alt-Ctrl-Semicolon: Alt-Ctrl-N
    Alt-Ctrl-Super-A: Alt-Ctrl-Super-A
    Alt-Ctrl-Super-B: Alt-Ctrl-Super-F
    Alt-Ctrl-Super-C: Alt-Ctrl-Super-C
    Alt-Ctrl-Super-Comma: Alt-Ctrl-Super-J
    Alt-Ctrl-Super-D: Alt-Ctrl-Super-E
    Alt-Ctrl-Super-Dot: Alt-Ctrl-Super-L
    Alt-Ctrl-Super-E: Alt-Ctrl-Super-Comma
    Alt-Ctrl-Super-F: Alt-Ctrl-Super-I
    Alt-Ctrl-Super-G: Alt-Ctrl-Super-U
    Alt-Ctrl-Super-H: Alt-Ctrl-Super-G
    Alt-Ctrl-Super-I: Alt-Ctrl-Super-D
    Alt-Ctrl-Super-J: Alt-Ctrl-Super-T
    Alt-Ctrl-Super-K: Alt-Ctrl-Super-K
    Alt-Ctrl-Super-L: Alt-Ctrl-Super-S
    Alt-Ctrl-Super-M: Alt-Ctrl-Super-H
    Alt-Ctrl-Super-N: Alt-Ctrl-Super-B
    Alt-Ctrl-Super-O: Alt-Ctrl-Super-Y
    Alt-Ctrl-Super-P: Alt-Ctrl-Super-P
    Alt-Ctrl-Super-Q: Alt-Ctrl-Super-Q
    Alt-Ctrl-Super-R: Alt-Ctrl-Super-Dot
    Alt-Ctrl-Super-S: Alt-Ctrl-Super-O
    Alt-Ctrl-Super-Semicolon: Alt-Ctrl-Super-N
    Alt-Ctrl-Super-T: Alt-Ctrl-Super-Semicolon
    Alt-Ctrl-Super-U: Alt-Ctrl-Super-R
    Alt-Ctrl-Super-V: Alt-Ctrl-Super-V
    Alt-Ctrl-Super-X: Alt-Ctrl-Super-X
    Alt-Ctrl-Super-Y: Alt-Ctrl-Super-M
    Alt-Ctrl-Super-Z: Alt-Ctrl-Super-Z
    Alt-Ctrl-T: Alt-Ctrl-Semicolon
    Alt-Ctrl-U: Alt-Ctrl-R
    Alt-Ctrl-V: Alt-Ctrl-V
    Alt-Ctrl-X: Alt-Ctrl-X
    Alt-Ctrl-Y: Alt-Ctrl-M
    Alt-Ctrl-Z: Alt-Ctrl-Z
    Alt-D: Alt-E
    Alt-Dot: Alt-L
    Alt-E: Alt-Comma
    Alt-F: Alt-I
    Alt-G: Alt-U
    Alt-H: Alt-G
    Alt-I: Alt-D
    Alt-J: Alt-T
    Alt-K: Alt-K
    Alt-L: Alt-S
    Alt-M: Alt-H
    Alt-N: Alt-B
    Alt-O: Alt-Y
    Alt-P: Alt-P
    Alt-Q: Alt-Q
    Alt-R: Alt-Dot
    Alt-S: Alt-O
    Alt-Semicolon: Alt-N
    Alt-Super-A: Alt-Super-A
    Alt-Super-B: Alt-Super-F
    Alt-Super-C: Alt-Super-C
    Alt-Super-Comma: Alt-Super-J
    Alt-Super-D: Alt-Super-E
    Alt-Super-Dot: Alt-Super-L
    Alt-Super-E: Alt-Super-Comma
    Alt-Super-F: Alt-Super-I
    Alt-Super-G: Alt-Super-U
    Alt-Super-H: Alt-Super-G
    Alt-Super-I: Alt-Super-D
    Alt-Super-J: Alt-Super-T
    Alt-Super-K: Alt-Super-K
    Alt-Super-L: Alt-Super-S
    Alt-Super-M: Alt-Super-H
    Alt-Super-N: Alt-Super-B
    Alt-Super-O: Alt-Super-Y
    Alt-Super-P: Alt-Super-P
    Alt-Super-Q: Alt-Super-Q
    Alt-Super-R: Alt-Super-Dot
    Alt-Super-S: Alt-Super-O
    Alt-Super-Semicolon: Alt-Super-N
    Alt-Super-T: Alt-Super-Semicolon
    Alt-Super-U: Alt-Super-R
    Alt-Super-V: Alt-Super-V
    Alt-Super-X: Alt-Super-X
    Alt-Super-Y: Alt-Super-M
    Alt-Super-Z: Alt-Super-Z
    Alt-T: Alt-Semicolon
    Alt-U: Alt-R
    Alt-V: Alt-V
    Alt-X: Alt-X
    Alt-Y: Alt-M
    Alt-Z: Alt-Z
    B: F
    C: C
    Comma: J
    Ctrl-A: Ctrl-A
    Ctrl-B: Ctrl-F
    Ctrl-C: Ctrl-C
    Ctrl-Comma: Ctrl-J
    Ctrl-D: Ctrl-E
    Ctrl-Dot: Ctrl-L
    Ctrl-E: Ctrl-Comma
    Ctrl-F: Ctrl-I
    Ctrl-G: Ctrl-U
    Ctrl-H: Ctrl-G
    Ctrl-I: Ctrl-D
    Ctrl-J: Ctrl-T
    Ctrl-K: Ctrl-K
    Ctrl-L: Ctrl-S
    Ctrl-M: Ctrl-H
    Ctrl-N: Ctrl-B
    Ctrl-O: Ctrl-Y
    Ctrl-P: Ctrl-P
    Ctrl-Q: Ctrl-Q
    Ctrl-R: Ctrl-Dot
    Ctrl-S: Ctrl-O
    Ctrl-Semicolon: Ctrl-N
    Ctrl-Super-A: Ctrl-Super-A
    Ctrl-Super-B: Ctrl-Super-F
    Ctrl-Super-C: Ctrl-Super-C
    Ctrl-Super-Comma: Ctrl-Super-J
    Ctrl-Super-D: Ctrl-Super-E
    Ctrl-Super-Dot: Ctrl-Super-L
    Ctrl-Super-E: Ctrl-Super-Comma
    Ctrl-Super-F: Ctrl-Super-I
    Ctrl-Super-G: Ctrl-Super-U
    Ctrl-Super-H: Ctrl-Super-G
    Ctrl-Super-I: Ctrl-Super-D
    Ctrl-Super-J: Ctrl-Super-T
    Ctrl-Super-K: Ctrl-Super-K
    Ctrl-Super-L: Ctrl-Super-S
    Ctrl-Super-M: Ctrl-Super-H
    Ctrl-Super-N: Ctrl-Super-B
    Ctrl-Super-O: Ctrl-Super-Y
    Ctrl-Super-P: Ctrl-Super-P
    Ctrl-Super-Q: Ctrl-Super-Q
    Ctrl-Super-R: Ctrl-Super-Dot
    Ctrl-Super-S: Ctrl-Super-O
    Ctrl-Super-Semicolon: Ctrl-Super-N
    Ctrl-Super-T: Ctrl-Super-Semicolon
    Ctrl-Super-U: Ctrl-Super-R
    Ctrl-Super-V: Ctrl-Super-V
    Ctrl-Super-X: Ctrl-Super-X
    Ctrl-Super-Y: Ctrl-Super-M
    Ctrl-Super-Z: Ctrl-Super-Z
    Ctrl-T: Ctrl-Semicolon
    Ctrl-U: Ctrl-R
    Ctrl-V: Ctrl-V
    Ctrl-X: Ctrl-X
    Ctrl-Y: Ctrl-M
    Ctrl-Z: Ctrl-Z
    D: E
    Dot: L
    E: Comma
    F: I
    G: U
    H: G
    I: D
    J: T
    K: K
    L: S
    M: H
    N: B
    O: Y
    P: P
    Q: Q
    R: Dot
    S: O
    Semicolon: N
    Shift-A: Shift-A
    Shift-Alt-A: Shift-Alt-A
    Shift-Alt-B: Shift-Alt-F
    Shift-Alt-C: Shift-Alt-C
    Shift-Alt-Comma: Shift-Alt-J
    Shift-Alt-Ctrl-A: Shift-Alt-Ctrl-A
    Shift-Alt-Ctrl-B: Shift-Alt-Ctrl-F
    Shift-Alt-Ctrl-C: Shift-Alt-Ctrl-C
    Shift-Alt-Ctrl-Comma: Shift-Alt-Ctrl-J
    Shift-Alt-Ctrl-D: Shift-Alt-Ctrl-E
    Shift-Alt-Ctrl-Dot: Shift-Alt-Ctrl-L
    Shift-Alt-Ctrl-E: Shift-Alt-Ctrl-Comma
    Shift-Alt-Ctrl-F: Shift-Alt-Ctrl-I
    Shift-Alt-Ctrl-G: Shift-Alt-Ctrl-U
    Shift-Alt-Ctrl-H: Shift-Alt-Ctrl-G
    Shift-Alt-Ctrl-I: Shift-Alt-Ctrl-D
    Shift-Alt-Ctrl-J: Shift-Alt-Ctrl-T
    Shift-Alt-Ctrl-K: Shift-Alt-Ctrl-K
    Shift-Alt-Ctrl-L: Shift-Alt-Ctrl-S
    Shift-Alt-Ctrl-M: Shift-Alt-Ctrl-H
    Shift-Alt-Ctrl-N: Shift-Alt-Ctrl-B
    Shift-Alt-Ctrl-O: Shift-Alt-Ctrl-Y
    Shift-Alt-Ctrl-P: Shift-Alt-Ctrl-P
    Shift-Alt-Ctrl-Q: Shift-Alt-Ctrl-Q
    Shift-Alt-Ctrl-R: Shift-Alt-Ctrl-Dot
    Shift-Alt-Ctrl-S: Shift-Alt-Ctrl-O
    Shift-Alt-Ctrl-Semicolon: Shift-Alt-Ctrl-N
    Shift-Alt-Ctrl-Super-A: Shift-Alt-Ctrl-Super-A
    Shift-Alt-Ctrl-Super-B: Shift-Alt-Ctrl-Super-F
    Shift-Alt-Ctrl-Super-C: Shift-Alt-Ctrl-Super-C
    Shift-Alt-Ctrl-Super-Comma: Shift-Alt-Ctrl-Super-J
    Shift-Alt-Ctrl-Super-D: Shift-Alt-Ctrl-Super-E
    Shift-Alt-Ctrl-Super-Dot: Shift-Alt-Ctrl-Super-L
    Shift-Alt-Ctrl-Super-E: Shift-Alt-Ctrl-Super-Comma
    Shift-Alt-Ctrl-Super-F: Shift-Alt-Ctrl-Super-I
    Shift-Alt-Ctrl-Super-G: Shift-Alt-Ctrl-Super-U
    Shift-Alt-Ctrl-Super-H: Shift-Alt-Ctrl-Super-G
    Shift-Alt-Ctrl-Super-I: Shift-Alt-Ctrl-Super-D
    Shift-Alt-Ctrl-Super-J: Shift-Alt-Ctrl-Super-T
    Shift-Alt-Ctrl-Super-K: Shift-Alt-Ctrl-Super-K
    Shift-Alt-Ctrl-Super-L: Shift-Alt-Ctrl-Super-S
    Shift-Alt-Ctrl-Super-M: Shift-Alt-Ctrl-Super-H
    Shift-Alt-Ctrl-Super-N: Shift-Alt-Ctrl-Super-B
    Shift-Alt-Ctrl-Super-O: Shift-Alt-Ctrl-Super-Y
    Shift-Alt-Ctrl-Super-P: Shift-Alt-Ctrl-Super-P
    Shift-Alt-Ctrl-Super-Q: Shift-Alt-Ctrl-Super-Q
    Shift-Alt-Ctrl-Super-R: Shift-Alt-Ctrl-Super-Dot
    Shift-Alt-Ctrl-Super-S: Shift-Alt-Ctrl-Super-O
    Shift-Alt-Ctrl-Super-Semicolon: Shift-Alt-Ctrl-Super-N
    Shift-Alt-Ctrl-Super-T: Shift-Alt-Ctrl-Super-Semicolon
    Shift-Alt-Ctrl-Super-U: Shift-Alt-Ctrl-Super-R
    Shift-Alt-Ctrl-Super-V: Shift-Alt-Ctrl-Super-V
    Shift-Alt-Ctrl-Super-X: Shift-Alt-Ctrl-Super-X
    Shift-Alt-Ctrl-Super-Y: Shift-Alt-Ctrl-Super-M
    Shift-Alt-Ctrl-Super-Z: Shift-Alt-Ctrl-Super-Z
    Shift-Alt-Ctrl-T: Shift-Alt-Ctrl-Semicolon
    Shift-Alt-Ctrl-U: Shift-Alt-Ctrl-R
    Shift-Alt-Ctrl-V: Shift-Alt-Ctrl-V
    Shift-Alt-Ctrl-X: Shift-Alt-Ctrl-X
    Shift-Alt-Ctrl-Y: Shift-Alt-Ctrl-M
    Shift-Alt-Ctrl-Z: Shift-Alt-Ctrl-Z
    Shift-Alt-D: Shift-Alt-E
    Shift-Alt-Dot: Shift-Alt-L
    Shift-Alt-E: Shift-Alt-Comma
    Shift-Alt-F: Shift-Alt-I
    Shift-Alt-G: Shift-Alt-U
    Shift-Alt-H: Shift-Alt-G
    Shift-Alt-I: Shift-Alt-D
    Shift-Alt-J: Shift-Alt-T
    Shift-Alt-K: Shift-Alt-K
    Shift-Alt-L: Shift-Alt-S
    Shift-Alt-M: Shift-Alt-H
    Shift-Alt-N: Shift-Alt-B
    Shift-Alt-O: Shift-Alt-Y
    Shift-Alt-P: Shift-Alt-P
    Shift-Alt-Q: Shift-Alt-Q
    Shift-Alt-R: Shift-Alt-Dot
    Shift-Alt-S: Shift-Alt-O
    Shift-Alt-Semicolon: Shift-Alt-N
    Shift-Alt-Super-A: Shift-Alt-Super-A
    Shift-Alt-Super-B: Shift-Alt-Super-F
    Shift-Alt-Super-C: Shift-Alt-Super-C
    Shift-Alt-Super-Comma: Shift-Alt-Super-J
    Shift-Alt-Super-D: Shift-Alt-Super-E
    Shift-Alt-Super-Dot: Shift-Alt-Super-L
    Shift-Alt-Super-E: Shift-Alt-Super-Comma
    Shift-Alt-Super-F: Shift-Alt-Super-I
    Shift-Alt-Super-G: Shift-Alt-Super-U
    Shift-Alt-Super-H: Shift-Alt-Super-G
    Shift-Alt-Super-I: Shift-Alt-Super-D
    Shift-Alt-Super-J: Shift-Alt-Super-T
    Shift-Alt-Super-K: Shift-Alt-Super-K
    Shift-Alt-Super-L: Shift-Alt-Super-S
    Shift-Alt-Super-M: Shift-Alt-Super-H
    Shift-Alt-Super-N: Shift-Alt-Super-B
    Shift-Alt-Super-O: Shift-Alt-Super-Y
    Shift-Alt-Super-P: Shift-Alt-Super-P
    Shift-Alt-Super-Q: Shift-Alt-Super-Q
    Shift-Alt-Super-R: Shift-Alt-Super-Dot
    Shift-Alt-Super-S: Shift-Alt-Super-O
    Shift-Alt-Super-Semicolon: Shift-Alt-Super-N
    Shift-Alt-Super-T: Shift-Alt-Super-Semicolon
    Shift-Alt-Super-U: Shift-Alt-Super-R
    Shift-Alt-Super-V: Shift-Alt-Super-V
    Shift-Alt-Super-X: Shift-Alt-Super-X
    Shift-Alt-Super-Y: Shift-Alt-Super-M
    Shift-Alt-Super-Z: Shift-Alt-Super-Z
    Shift-Alt-T: Shift-Alt-Semicolon
    Shift-Alt-U: Shift-Alt-R
    Shift-Alt-V: Shift-Alt-V
    Shift-Alt-X: Shift-Alt-X
    Shift-Alt-Y: Shift-Alt-M
    Shift-Alt-Z: Shift-Alt-Z
    Shift-B: Shift-F
    Shift-C: Shift-C
    Shift-Comma: Shift-J
    Shift-Ctrl-A: Shift-Ctrl-A
    Shift-Ctrl-B: Shift-Ctrl-F
    Shift-Ctrl-C: Shift-Ctrl-C
    Shift-Ctrl-Comma: Shift-Ctrl-J
    Shift-Ctrl-D: Shift-Ctrl-E
    Shift-Ctrl-Dot: Shift-Ctrl-L
    Shift-Ctrl-E: Shift-Ctrl-Comma
    Shift-Ctrl-F: Shift-Ctrl-I
    Shift-Ctrl-G: Shift-Ctrl-U
    Shift-Ctrl-H: Shift-Ctrl-G
    Shift-Ctrl-I: Shift-Ctrl-D
    Shift-Ctrl-J: Shift-Ctrl-T
    Shift-Ctrl-K: Shift-Ctrl-K
    Shift-Ctrl-L: Shift-Ctrl-S
    Shift-Ctrl-M: Shift-Ctrl-H
    Shift-Ctrl-N: Shift-Ctrl-B
    Shift-Ctrl-O: Shift-Ctrl-Y
    Shift-Ctrl-P: Shift-Ctrl-P
    Shift-Ctrl-Q: Shift-Ctrl-Q
    Shift-Ctrl-R: Shift-Ctrl-Dot
    Shift-Ctrl-S: Shift-Ctrl-O
    Shift-Ctrl-Semicolon: Shift-Ctrl-N
    Shift-Ctrl-Super-A: Shift-Ctrl-Super-A
    Shift-Ctrl-Super-B: Shift-Ctrl-Super-F
    Shift-Ctrl-Super-C: Shift-Ctrl-Super-C
    Shift-Ctrl-Super-Comma: Shift-Ctrl-Super-J
    Shift-Ctrl-Super-D: Shift-Ctrl-Super-E
    Shift-Ctrl-Super-Dot: Shift-Ctrl-Super-L
    Shift-Ctrl-Super-E: Shift-Ctrl-Super-Comma
    Shift-Ctrl-Super-F: Shift-Ctrl-Super-I
    Shift-Ctrl-Super-G: Shift-Ctrl-Super-U
    Shift-Ctrl-Super-H: Shift-Ctrl-Super-G
    Shift-Ctrl-Super-I: Shift-Ctrl-Super-D
    Shift-Ctrl-Super-J: Shift-Ctrl-Super-T
    Shift-Ctrl-Super-K: Shift-Ctrl-Super-K
    Shift-Ctrl-Super-L: Shift-Ctrl-Super-S
    Shift-Ctrl-Super-M: Shift-Ctrl-Super-H
    Shift-Ctrl-Super-N: Shift-Ctrl-Super-B
    Shift-Ctrl-Super-O: Shift-Ctrl-Super-Y
    Shift-Ctrl-Super-P: Shift-Ctrl-Super-P
    Shift-Ctrl-Super-Q: Shift-Ctrl-Super-Q
    Shift-Ctrl-Super-R: Shift-Ctrl-Super-Dot
    Shift-Ctrl-Super-S: Shift-Ctrl-Super-O
    Shift-Ctrl-Super-Semicolon: Shift-Ctrl-Super-N
    Shift-Ctrl-Super-T: Shift-Ctrl-Super-Semicolon
    Shift-Ctrl-Super-U: Shift-Ctrl-Super-R
    Shift-Ctrl-Super-V: Shift-Ctrl-Super-V
    Shift-Ctrl-Super-X: Shift-Ctrl-Super-X
    Shift-Ctrl-Super-Y: Shift-Ctrl-Super-M
    Shift-Ctrl-Super-Z: Shift-Ctrl-Super-Z
    Shift-Ctrl-T: Shift-Ctrl-Semicolon
    Shift-Ctrl-U: Shift-Ctrl-R
    Shift-Ctrl-V: Shift-Ctrl-V
    Shift-Ctrl-X: Shift-Ctrl-X
    Shift-Ctrl-Y: Shift-Ctrl-M
    Shift-Ctrl-Z: Shift-Ctrl-Z
    Shift-D: Shift-E
    Shift-Dot: Shift-L
    Shift-E: Shift-Comma
    Shift-F: Shift-I
    Shift-G: Shift-U
    Shift-H: Shift-G
    Shift-I: Shift-D
    Shift-J: Shift-T
    Shift-K: Shift-K
    Shift-L: Shift-S
    Shift-M: Shift-H
    Shift-N: Shift-B
    Shift-O: Shift-Y
    Shift-P: Shift-P
    Shift-Q: Shift-Q
    Shift-R: Shift-Dot
    Shift-S: Shift-O
    Shift-Semicolon: Shift-N
    Shift-Super-A: Shift-Super-A
    Shift-Super-B: Shift-Super-F
    Shift-Super-C: Shift-Super-C
    Shift-Super-Comma: Shift-Super-J
    Shift-Super-D: Shift-Super-E
    Shift-Super-Dot: Shift-Super-L
    Shift-Super-E: Shift-Super-Comma
    Shift-Super-F: Shift-Super-I
    Shift-Super-G: Shift-Super-U
    Shift-Super-H: Shift-Super-G
    Shift-Super-I: Shift-Super-D
    Shift-Super-J: Shift-Super-T
    Shift-Super-K: Shift-Super-K
    Shift-Super-L: Shift-Super-S
    Shift-Super-M: Shift-Super-H
    Shift-Super-N: Shift-Super-B
    Shift-Super-O: Shift-Super-Y
    Shift-Super-P: Shift-Super-P
    Shift-Super-Q: Shift-Super-Q
    Shift-Super-R: Shift-Super-Dot
    Shift-Super-S: Shift-Super-O
    Shift-Super-Semicolon: Shift-Super-N
    Shift-Super-T: Shift-Super-Semicolon
    Shift-Super-U: Shift-Super-R
    Shift-Super-V: Shift-Super-V
    Shift-Super-X: Shift-Super-X
    Shift-Super-Y: Shift-Super-M
    Shift-Super-Z: Shift-Super-Z
    Shift-T: Shift-Semicolon
    Shift-U: Shift-R
    Shift-V: Shift-V
    Shift-X: Shift-X
    Shift-Y: Shift-M
    Shift-Z: Shift-Z
    Super-A: Super-A
    Super-B: Super-F
    Super-C: Super-C
    Super-Comma: Super-J
    Super-D: Super-E
    Super-Dot: Super-L
    Super-E: Super-Comma
    Super-F: Super-I
    Super-G: Super-U
    Super-H: Super-G
    Super-I: Super-D
    Super-J: Super-T
    Super-K: Super-K
    Super-L: Super-S
    Super-M: Super-H
    Super-N: Super-B
    Super-O: Super-Y
    Super-P: Super-P
    Super-Q: Super-Q
    Super-R: Super-Dot
    Super-S: Super-O
    Super-Semicolon: Super-N
    Super-T: Super-Semicolon
    Super-U: Super-R
    Super-V: Super-V
    Super-X: Super-X
    Super-Y: Super-M
    Super-Z: Super-Z
    T: Semicolon
    U: R
    V: V
    X: X
    Y: M
    Z: Z
modmap:
- name: xremap-python
  remap:
    Alt_R: Super_L
    CapsLock: Control_L

